services:
  - type: web_service
    name: nexus-premium-bot-v5
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        value: 7946266426:AAHo9m9fWsU7Fqf-p_LYnMKB6KrCMPV23u8
      - key: OWNER_ID
        value: "7702588711"
      - key: ADMIN_IDS
        value: "7702588711,8526073588"
